name: build

on:
  pull_request:
    branches:
      - master
      - release
      - 2.0

jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v1
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - name: Install Dependencies
        run: npm install
      - name: Commit Linter
        uses: wagoid/commitlint-github-action@v1.2.2
        with:
          configFile: '.commitlintrc.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run ESLinter
        run: npm run lint
      - name: Run Tests
        run: npm test
      - name: Run Code Coverage
        run: npm run coverage
